export type EEnvVariable =
    "BOT_TOKEN" |
    "CHAT_NUMBER" |
    "PORT" |
    "ACADEMY_EMAIL" |
    "ACADEMY_PWD" |
    "ACADEMY_CHAT" |
    "ACADEMY_SECOND" |
    "KRAKEN_DB_CONNECT" |
    "KRAKEN_API_KEY" |
    "KRAKEN_API_SIGN" |
    "LOGFILE_PATH"


export enum EArgvVariable {
  BOT_TOKEN = 2,
  CHAT_NUMBER,
  PORT,
  LOGFILE_PATH,

  ACADEMY_EMAIL,
  ACADEMY_PWD,
  ACADEMY_CHAT,
  ACADEMY_SECOND,

  KRAKEN_DB_CONNECT,
  KRAKEN_API_KEY,
  KRAKEN_API_SIGN
}

export const ArgvMap: Record<EEnvVariable, EArgvVariable> = {
  BOT_TOKEN: 2,
  CHAT_NUMBER: 3,
  PORT: 4,
  LOGFILE_PATH: 5,

  ACADEMY_EMAIL: 6,
  ACADEMY_PWD: 7,
  ACADEMY_CHAT: 8,
  ACADEMY_SECOND: 9,

  KRAKEN_DB_CONNECT: 10,
  KRAKEN_API_KEY: 11,
  KRAKEN_API_SIGN: 12,
};
